id: P004440
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:21:52.386600
source_metadata:
  id: bdr:W4CZ58511
  title: མདོ་སྡེ་བསྐལ་བཟང་།
  author: ''
  volumes:
    e17044233fb049d7ad5ceab7adb76048:
      image_group_id: I4CZ58826
      title: ''
      volume_number: 1
      total_pages: 1045
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
